name: Python Workflow for Sum Frequencies Application
on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        version: [3.7, 3.8, 3.9, 3.10]
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            version:: 3.6
        exclude:
          - os: windows-latest
            version:: 3.10
            
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: ${{ version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 /Ch02/02-04-challenge-use-a-matrix-strategy-to-test-an-application --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 ./Ch02/02-04-challenge-use-a-matrix-strategy-to-test-an-application --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test the application with mock data
      run: |
        python ./Ch02/02-04-challenge-use-a-matrix-strategy-to-test-an-application/sum_frequencies.py MOCK_DATA.json
