name: Matrix-Python Test
on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    #----------------------------------------------#
    # Add your matrix strategy configuration here  #
    #----------------------------------------------#
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install -r ./Ch02/02-04-challenge-use-a-matrix-strategy-to-test-an-application/requirements.txt
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 ./Ch02/02-04-challenge-use-a-matrix-strategy-to-test-an-application --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 ./Ch02/02-04-challenge-use-a-matrix-strategy-to-test-an-application --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test the application with mock data
      run: |
        python ./Ch02/02-04-challenge-use-a-matrix-strategy-to-test-an-application/sum_frequencies.py ./Ch02/02-04-challenge-use-a-matrix-strategy-to-test-an-application/MOCK_DATA.json
