name: Use Composite Action
on:

  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
        
      - uses: ./.github/actions/check-python
        with:
          PYTHON_VERSION: 3.8
