name: Use Composite Action
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/check-python@main
        with:
          PYTHON_VERSION: 3.8
